baseURL = "https://SrividyaSuresh.github.io/PagesBlog/"
languageCode = "en-us"
title = "To Echo The World"
theme = "bear"
publishDir = "public"

[params]
  author = "Srividya Suresh"
  description = "Blogs and some such"

[menu]

  [[menu.main]]
  identifier = "home"
  name = "Home"
  url = "/"
  weight = 1

  [[menu.main]]
  identifier = "blog"
  name = "Blog"
  url = "/blog/"
  weight = 2

  [[menu.main]]
  identifier = "books"
  name = "Books"
  url = "/books/"
  weight = 3

  [[menu.main]]
  identifier = "random"
  name = "Random"
  url = "/random/"
  weight = 4
